# Generated by Django 5.2.7 on 2025-10-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CM_app', '0002_remove_profile_role_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
